spring:
  datasource:
    url: jdbc:postgresql://aarti-private-postgres-db.cafhcpgcbext.us-east-2.rds.amazonaws.com:5432/postgres
    username: example/postgres/username
    password: example/postgres/password
    driverClassName: org.postgresql.Driver
  main:
    banner_mode: off
  session:
    jdbc:
      initialize_schema: always
  sql:
    init:
      mode: always
      platform: postgres
      continue_on_error: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        use_sql_comments: true
        dialect  : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
        ddl_auto  : none
    show_sql: true
    generate_ddl: true
    defer_datasource_initialization: true
actuator_username: example/actuator/username
actuator_password: example/actuator/password
logging:
  level:
    org:
      springframework: DEBUG