spring:
  datasource:
    url: jdbc:postgresql://aarti-private-postgres-db.cafhcpgcbext.us-east-2.rds.amazonaws.com:5432/postgres
    username: example/postgres/username
    password: example/postgres/password
    driverClassName: org.postgresql.Driver
  main:
    banner-mode: off
  session:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        use_sql_comments: true
        dialect  : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
        ddl-auto  : none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
actuator_username: example/actuator/username
actuator_password: example/actuator/password
logging:
  level:
    org:
      springframework: DEBUG